root = "."
tmp_dir = "tmp"

[build]
  entrypoint = "./tmp/main"
  cmd = "go build -o ./tmp/main server.go"
  exclude_dir = ["node_modules","tmp", "vendor"]
  include_dir = ["ui"]
  include_ext = ["go"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"
